import YXT.Axiomatic.T64
import YXT.Axiomatic.Cl6
import YXT.Axiomatic.NoOutside
import YXT.Axiomatic.SixLaws
import YXT.Axiomatic.Reduction35
import YXT.Axiomatic.GenerateA
import YXT.Ontology.FourLayer
import YXT.StandardTheory.Cyclotomic85
import YXT.HeartField.PsiSR
